
services:
  redis:
    image: redis:7-alpine
    container_name: redis-car-wash-cache
    restart: unless-stopped
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD:-your_redis_password}"]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD:-your_redis_password}", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  redis-data:
    name: car-rental-redis-data
